### PR TITLE
Add "files" to "package.json"

### PR DESCRIPTION
**Pull request by zertosh**
Specify what files to include in npm releases - this way `tests` and `bower.json` don't get included in the packaged version. (See https://docs.npmjs.com/files/package.json#files)

### CODE REVIEW

**Comment by ScottHamper** [comment]
Cool, thanks Andres!

**Comment by ScottHamper** [comment]
Hey, what are your thoughts about reducing the list of files even further? Specifically, removing the "src" folder and "CHANGELOG.md"?

If the "files" property is intended to only include files that are relevant for a production ready package, then it seems like it would make sense to only include the "dist" folder. Is there a semantic difference between "tests" and "src" that means we should treat them differently from each other? They both seem like they'd only be relevant when doing development work on the library.

Let me know what you think!

**Comment by zertosh** [comment]
Hey @ScottHamper, np. I have no opinion on `CHANGELOG.md`, but yeah `src` should be excluded too - I missed it.

**Comment by ScottHamper** [comment]
Ok, cool! Thanks again

**Comment by zertosh** [comment]
Not sure how familiar you are with `npm`, so I hope I'm not offending by offering this tip: You can see what your final package will look like by running `npm pack`. It'll make `tar.gz` that you can then open and inspect to make sure everything you expect to be there is actually there.

**Comment by ScottHamper** [comment]
Nice! That's great to know - I am not really that familiar with NPM. I'll have to prepare a new release with these changes soon.

**Pull request merged**
